default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: rails_api_example_development

test:
  <<: *default
  database: rails_api_example_test

production:
  <<: *default
  database: rails_api_example_production
